### ISSUE TITLE
Create Data Transfer Objects (DTO) for each entity class

### ISSUE THREAD

**Issue by jorgenfinsveen** [Group10-IDATA2301-IDATA2306/Mocha-cafe#49]
See the usage of DTO on this <a href="https://www.geeksforgeeks.org/data-transfer-object-dto-in-spring-mvc-with-example/">GeeksForGeeks article</a>.

**Comment by ejhasler** [comment]
Added Data Transfer Object for the needed class, maybe some implementations can be needed or classes, can be done later, but this issue is good for now.
